### ISSUE TITLE
Migration and mass creating models

### ISSUE THREAD

**Issue by fetova** [barryvdh/laravel-migration-generator#13]
Hi!

There is a way to mass create models on the same way that are created the migrations tables? Nothing too complex, just the file with table name within it.

Thanks!

**Comment by barryvdh** [comment]
Not yet, but will keep this is mind when creating a new version using the
2.X generators.
Op 7 mrt. 2014 19:00 schreef "fetova" notifications@github.com:

**Comment by fetova** [comment]
Thanks a lot!

This project saved me a lot of time, really appreciated :)
