### ISSUE TITLE
Compatibility with Laravel 4.1

### ISSUE THREAD

**Issue by wes-nz** [barryvdh/laravel-migration-generator#6]
Hello,

i used this package few times without any problems. 
Unfortunately, since the update of Laravel I now have an error message 

{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found","file":"\/Users\/----------/Website\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/MySqlConnection.php","line":59}}{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found","file":"\/Users------------/Website\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/MySqlConnection.php","line":59}}

I think there is a problem with database drivers... any ideas ? 
Thanks a lot.

**Comment by barryvdh** [comment]
Yeah doctrine isn't included by default in 4.1. Added it to composer, so should work in a few minutes.
(Or you can also add the doctrine dependancy to your project )

**Comment by wes-nz** [comment]
Wow ! fastest answer/commit of the history. 
Yep, working like a charm.
Thanks Flash Gordon ;)

**Comment by ragsnas** [comment]
since it is not just as simple as `use doctrine` i think this might help some peopel arriving here  via search:
`"doctrine/dbal": "~2.3"`

**Comment by sanjay23** [comment]
i added  "doctrine/dbal": "~2.3" but still not working i geeting this type of error:

Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found in /var/www/html/eventerprise/vendor/laravel/framework/src/Illuminate/Database/MySqlConnection.php on line 59
{"error":{"type":"Symfony\Component\Debug\Exception\FatalErrorException","message":"Class 'Doctrine\DBAL\Driver\PDOMySql\Driver' not found","file":"\/var\/www\/html\/eventerprise\/vendor\/laravel\/framework\/src\/Illuminate\/Database\/MySqlConnection.php","line":59}}
Please any one give solution....

**Comment by barryvdh** [comment]
And did you run composer update?

**Comment by sanjay23** [comment]
No i geeting this type of  error -bash: composer: command not found

**Comment by barryvdh** [comment]
https://getcomposer.org/doc/00-intro.md#installation-nix

**Comment by sanjay23** [comment]
Thnks it's working...
