### ISSUE TITLE
Bit Type Failure

### ISSUE THREAD

**Issue by ryanburst** [barryvdh/laravel-migration-generator#9]
This issue is similar to <a href="https://github.com/barryvdh/laravel-migration-generator/issues/3"> Issue 3</a>. Bit type fields throw an exception:

<code>
[Doctrine\DBAL\DBALException]  
  Unknown database type bit requested, Doctrine\DBAL\Platforms\MySqlPlatform may not support it.
</code>

I believe registering a <code>bit</code> as a <code>boolean</code> should fix the problem:
$schema->getDatabasePlatform()->registerDoctrineTypeMapping('bit', 'boolean');

Noted from <a href="http://stackoverflow.com/questions/9744629/doctrine2-workaround-for-mapping-mysql-bit-data-type">this StackOverflow question</a>

There is also a possibility that you could extract a list of converted types into a property that can be overridden by extending your migration class. This way people can feel free to register types to their convenience.

**Comment by barryvdh** [comment]
Can you test and create a PR?
Op 4 mrt. 2014 21:44 schreef "ryanburst" notifications@github.com:

**Comment by ryanburst** [comment]
Tested and submitted <a href="https://github.com/barryvdh/laravel-migration-generator/pull/10">pull request</a>.

**Comment by ryanburst** [comment]
PR accepted, closing down this issue.
